---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgC7YwONtpEJ6RXKQXBzTI/xWqWU5tNXy2vVBDcFYMjQCjuELebCsc6laC2Yzw+SsYuO14mhIbPd7ppDbJlq6vzmfTfxeww4HaHvjIU6uP0C1C2fTiGBqAAiFEts801WMklS6D4WLFeReJV7VNXaTECzEwn9OO1WfXCD7syWE6SByQDQiqnrD6qu5+gfb4t2vd6r5j8kUUrfvkKSCB7Ye7RGulgOPnm2gDDfumQIpn2euk5agqQxVuplY1YczK4fgtKWCDyOOlNgb/VcpMKTWUEx1ci+/xCM3zIF9rY5Bq69OZhuhbQncDNaPXodVAq1RbI5WHlT3i9S+AyuFANdrRtptzXSJh4HWHAB0MbQMEqdIGI4wBSE8PnCqR7IItPT/hWLj6ljPOr+fCjXQyhkpfCtln+rgrO3J/uzWeEqTBeJr2RtXnmGrEoxa2hmDsstbEanOVzfUE0QfQewKkf1alQersIXtwGRkajdK9PshVzCbFN9BsRbS0hc6cY27+Fg4/YATnPnrNSr2wXcugBJ/C8j/1TPtfeLT1qN9qhLSHSOczuGNn/HOUGaNRHWroTv6A801vs0c9s/enf54jqZqdxQHDFl2Nqa0mCc2uY1KFWVhbg9HKhY4UgDjmje3Ts9uDmZ/aj9YCdR1P494LVVdqGO3e6UIzLWT2rdu1y6mRDRhvN0xesJfgHr/4Xt9E9KzpuGDBcopk5RDo4f0mlYAisZ/rncaIGSJdf7REhLWn8oF3p35Kz0/GK+G2F3T8Jq/rckK2xiXUeJcUp7+qKPhM5xXkYDwZP0S4WI0i+Vi/Bf3pXl+MDBtT/WxDJ+TXDWjoKzRJFL7o6WSzWV4m0Vrg+C6ch4EOKLFkgw
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
