apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portfolio
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-portfolio
  template:
    metadata:
      labels:
        app: dev-portfolio
    spec:
      nodeSelector:
        homelab/node-role: worker
        homelab/power: non-ups
      tolerations:
        - key: homelab/power
          operator: Equal
          value: non-ups
          effect: NoSchedule
      containers:
        - name: dev-portfolio
          image: ghcr.io/pablomarelli/dev-portfolio:2026.5.23
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
