apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik/AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: authentik/AUTHENTIK_POSTGRESQL__PASSWORD
