---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-secrets
  namespace: monitoring
spec:
  encryptedData:
    DATABASE_URL: AgAKXRai6C1YwCaanuIYnS8CKpYAFgUSu+wWm0etLtnuHPE54H7KkbkdCdL5A06GLp/X3kY1xxVUFMZPGz4YajyvQuCQdErpuhS0HpXDS+53SpWND/a9k3pryiyQ/D3WLxVdM2W1DSGapDlsJxKPhrqDn5or/w4j7JHklJ7yTW5gRQd1WC8aWtCJ3P6RzEt8AKiYvRmoSoyqeoA7UISCcyff2jvSYPfyoL6lPe9j1KWx2tlXOZZ7q6+mreoOXMT4Z89nWReF4Nbv44lSVyf46UtjX75BjffwBKzjg/QiglsOaAtBVGVHi7tOCbro/GCgKvAhnH+VQsDc5ItCS1zhKG91vN+EokX3LD9MSmpshJP+dtBRg6POgOfJCw33kLQTU0lynECKmDD56bf0N88s4JDWHFPvwDQYl/i/IzFc9T6pKITi2Jt+LyGByQSzd4tAcKVjGziMUp50TmOzXDxBKDrazdH8BRBZJZbEt0fZcPUWCpElk6/9XmlCO4tSvqSLtVuPQMn7IvJ+B24hNcoD1fCwbPe11j1clZpynHG8itbc3LKKrM1grptR9yYnQcy5a21O9B79hrkYzqMAWFrLJ9JEpIRPQiwpCtWe23GxUjVKPOdtu8xqlZAqeZTeQraP63ZD2+Yplzn1E1iswbhmr9C+JDQY7r4ISss3rZ8QlQmLoz5feSa9uFSUcpaDD6HaoLbNf0G3MaBGX3v6c1kaLwNtgtqJbDITjZNfj8EzqOz2Rwv8rs2iffY5yjwc9pJ6/eAn3HGuU1MU60DUl4Zc3uk2FORBnxMmUt36A/YdiNPO5fsRIlg6jKVRbPLKDFCH4I7MQdFsiLE=
  template:
    metadata:
      name: umami-secrets
      namespace: monitoring
