---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-secrets
  namespace: monitoring
spec:
  encryptedData:
    DATABASE_URL: AgCYpLy/mRtPC7Kba7et+u2F3LHh2MurVKbPQv6aqu0iF4ztIB+z45wIdVe9hsIdwc/xcRvOECapvs88cHTZj2498U1g8K7CYbbVsMWuM+Q3po+4F82fTAGaKvHDF5UAXdW0wpYAGOyng9pZRO7poK3fVXiTCqrJQP5WvaGhSfN3R4AD8M6GN60P4VXkuJuL1m6epoUnQuwonYMPu53AZXzIpU0wTiBZvc7Qi4c1QoU9DjCpNQ/mPs7K/KnC9l+dNgiOekd5fL2lnrl6CAVXmFLO2Inxs/xdq3nFMt9UUCR4+YB8PGL1m2yTYD+0PK5DzyzshiTwWWNvY4yo96kthA0iuSaBcs90MaLvMesVn2jm0lLuqGM6dHgXyyvvcl+3t6FKP09ZLpQhI2CdBNawTM1r70nJ1OxMb3LDz32PEnl4bm3+vl4wLMCNYcsW+2Zu8QXEdD40bfMDPQPXeAVa0qhCDga9Ws7ruJvjQTssi6uHlt+UKIO6luDn/b2q3bOty+UouEQmLprYqpDR4bilnAZF/8jwdQCEqCDIsFGy5wUT0/t/R761rtgPU4ZciiWNwOAmth4rQ3xBH30fiTUDpdT9L53fOskhHm2uQGoToEZ0Jp8A6dNx+TJQBpQYLg9LoGxiRDv1lEnTtNRc2zvRpCra7l/zTm+ioGZwLRDEiME0i4dZEhUX2tqtSBczpd/NaI5ZSxhY3GbB60jzSWEHx0J257MpdpZNUXCrrGZ+fxdUke7E+1ouOCWCNONrJetaisyUls4DMTZ+YHfwZPvijqvdifznR/uTCtu2Dv17/SacJJi58y57heRSZTEBfegv1mpsCkLxlUqkyw==
  template:
    metadata:
      name: umami-secrets
      namespace: monitoring
