---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgAFTY6c79lbMognuPipqVIua4DU/DBf5NcV6otYBczgr37E+lCN8zbL1wnlynaYNJLRyuRiQ6PaUATZKiNyuYQUcFXHmxsp6ArCYV13wJHPQhKPIJoQ3qrqFrmigm9DD/dKJpFT7SXjwUrgs3ArxrJ/HGCDtqcnGTSCf2xA3b5l0jsOLacMNh0hVqcCbEY+8oLjywXxxTXhqPoEkGgzw4ewsDzN++G2vnVGo2JJNW/M/qOoRmuci6xn17U1t9gRAkdQl5dEbcFvtliOtnRYjmlqOFhTGrAbeBNwZ2NxBfPETKo0e7oRjk/vTwO1v07rib6JP3sU/NKjFrxLITAPOqZ0sg5DMOaJcE8PnK+F8j8ovZ5RKQ/9aCnRbf7oUOnC/5BZrRyaZlRox+i8k4B/NEqicpe4qu51qimbQj4cEOF80LTzrNk5Q5HbyIdWYE+gCiquCArXXTw+O7JFvX6zsYgdou7PY48eBgm+Au/K9aHVFfz+6RzH3KuMNjkPJxVXPIyql2sk3uiOmk5VHbXg866mQcsvhc7awClEdTEq4Hb6FFadCdAIprhSunSlIFTacPb5TqtYf4cDS+iHXGfgZEqcCxZH9FY2ZCQc/KePJXPGWKqMoZdLROP1hvpzHTdDyBPA+pan3Njdf/kmYVXecLxHrc9il/gLSwKlmEtfxPM++mxkeFrvDtR0qP4uv3k5FBifcR9RZtR3YFLH4DNjzbwSn3EumHYMMMOiMVXGEQzIKnBRs2RqroghSjoAtrjVI262M6F9zN5knTpFLlxnxpc2U/rHqQq8I8rf4kZXztR2CEQ24IDGpX1dan8TFu8Fkv23LgBQCkEASTKZ0fka+mwn8sSlenMFSiKB
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
