apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: ntfy-secrets
    creationPolicy: Owner
  data:
    - secretKey: NTFY_AUTH_USERS
      remoteRef:
        key: ntfy/NTFY_AUTH_USERS
    - secretKey: NTFY_AUTH_TOKENS
      remoteRef:
        key: ntfy/NTFY_AUTH_TOKENS
