apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: infrastructure
data:
  config.yaml: |
    tunnel: 4d2e246b-8c39-49cd-b89c-5ba89d0fd598
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: "*.pablomarelli.dev"
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
