apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: infrastructure
data:
  config.yaml: |
    tunnel: adcf61e7-1183-4ff4-9f77-b25fa8fed5fd
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: "*.pablomarelli.dev"
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
