apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: infrastructure
data:
  config.yaml: |
    ingress:
      - hostname: argocd.pablomarelli.dev
        service: https://argocd-server.argocd.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      - hostname: portfolio.pablomarelli.dev
        service: http://portfolio-svc.portfolio.svc.cluster.local:80
      - hostname: finance.pablomarelli.dev
        service: http://finance-svc.finance.svc.cluster.local:80
      - hostname: home.pablomarelli.dev
        service: http://home-assistant-svc.home-assistant.svc.cluster.local:8123
      - service: http_status:404
