---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: infrastructure
spec:
  encryptedData:
    credentials.json: AgBGbzypVRFzvoI5AGivBCFXshoUDy/CLovbDpH5YFWscfrJ8H3wibcwcoUlkufXCVelmXWzbdMPJslt5+/huXrVoFpWNvQjzmAWwW5yunqi+ddTNhCgSAAK+IhwgODRIJ0+apdtKOz3tEQ9ZY3GutVI5kbRRro6G6Thjjo9nYL2td8otgzvs1YFVqMN9Fh0um0St1sP6hAf47GG+4+3lWqSfvENY+wfMljxYTDXvhBV6Gl+ZlpN6ymXOcRLv6AXgXp5FafnWI2dYQ3T4+402PflkMoRiDBFAnjd9DmG6ZZAP0mHswx621lFA0HX5JWZVhO04CmcxBEjEIVk5QbqaAJxPi7VrLuzC5m0Rtlwd6WdZqVQL/6NO4RYYvmlAZjE6zDDAr7r8+74p1qGIhRczUfMF0garybD8Btk3hNzRdBk3OLR1QSO7CtEFg1yYsDNMNPZMCYQ1JAT7tPlSEi2ERE/b55vRwsyCY+uQYktEfS5QPV6RYj94WliACgklFwV7O68lAk5DeVAkD/BjhYAfDs4Jp0Nkb2oWKrHwBjgGJ9ELwEMsTwyNb310dJllig5DJLHTnZ3gsG4DxXDauhj0Ctz/7DY2viWMAb7dWMOg2TJQj0tVMWe/e6EpggjMvoSspGj/cYvlia72ElW8l+2waBxEQ3G42xqXBS2eYu8QUUornH5SE/yDYAwgRXes39CkfM0rttC1RSlicJ+KfcBohANj0TIQ6wfzWDSG1L0BrR3D1KIQTXxb9v91DBtgaLsoJA77ueer+vnTRTqGtr6b4UNqC4YaY1OFFIFx2/zweKz5N3uGBqnzhpHeFT+SWZw6rrSqNFk/nARaqR587CC7KVUJq6rAxZK5RqvN1gkVjRVdXuP9OD/ttgy6JO9NGDNabVB47L11oQPch7FikZpXYNoV0obYEo/teaD5DcPjjWp
  template:
    metadata:
      name: cloudflared-credentials
      namespace: infrastructure
