---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAqawetrAw4IgmnkA4t6pgiXgw9oKwkmwbRrcHmqijTsXJ83QcnKdy+qYcX1UxDEcsatyXlWJlQhoH2KUalDnsJu7PIHMahFyfFxW2E0HJihxNhNuOuFrYV4ywp7xeeTPgR1aupD5Mps6JobBkoEgM8sSP/TYNgSj//F+3KP3PJXHo5xwcOPeWMW6sjQT6nsVUS/OLnP0lO/Sz8YQeDimSS4TdbK0UUhRXPNicp67N3Fx8WIZJgFN5uhsM4rwy1bDO3LGZsZjU0ISoxPGykdWFsHAZ+LZKa+M0dOc5BVZx1/ruL2ice+ElTlUmI+0gcydECkomRjuyuqW914383duiLuFlSpjiqB3m+5euSfvQA+5PN5uOaJLU6gZgkJe8pXOky1Ic1y+Y1YhPc77eoY0vanxgAueVHoOt5sMQZD/bh53WBvD2HtvVG3FtJwiKRTH10wEUU2nrL3Tyh49MK8t+QeZ2ZpiIGfkNFyS8MUsrMAM3+ufltuqTYbSAyJh5zbIUHKoel5LqMR/+lConaClHCYeBSDUT8s9saldZeXxrAYtnDTsiWenSgtKWHmAGC7XQLrD6h80e7hGLDiIc3aO+1OtmWsA39Yy8aK9Vjpt65PXfMvsmJcmf2If5AWQOXNvLEqskRMqbotWQh+k8FmL9ukYjFwKfmDblPv2+66xdVEX49ttEKE6g3/+Jytf2DxIQIoK78XnBn/V+zmFbInun5/iyVFkYvNPnADAZuakbCOkJA8F52UNC602wWDr67Z2oIW+h6RY3VcnaRIqLw+PCKRZhAnnVfiUgFA5gkNTMFyIkG0yvcXFB5M/2tFDJpaxXgphiUfXDjtA0Gtirp0YrMN/zelvopmsEgfkXUADArfvg6cyzds75FEcRJlUtFWNVVzz/3GgZZlFIKXuMjItJ/ApTgdobMDjAz6ZostLsg
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
