---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-outpost-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgBv7EG1njOxAUQkka7SMGH/3eg5gTjIfQw0UGMLq8LRPTeyJZ1ozIdOdGXhRLd8q4BL9D51/7juuzI1uMiEiJ1Hv5R7sWfFFvLbj4/mdv3uYTzIR1B5XkO3S4OnINqFfEsuTTMkwIjky+RnUt5AwJS+RITd9jhFIcokj23TSe0FtWPxVzjvepzIVVcNMybbkqU2QVe3LpfRAjE2bkw4jR0gPQvTTFRL+Qv7P9GVhRGpJbuvVARzt5xiuMspcXb7Umf83uaICsADAin3x3mlb3pSR3KH/C+2Yl8bx6fZi0cEp5XOl4Rg/5hSA7vq44OkQ9MD9FsyT6197Ui2x7ITGreziwkIGp/vJsAsnhNcti1MVX9ig7xSKXwXS6bDH4fF+ef9aEGXZAx0GfQB5o/p5q1XOpNg03L8zSoCu7dK3O9OH1fXJdomGk3IFSFYny/HU54FBna7NT/M/K3yvf1GGef0/uPFSeoXfrNNCYTg/OFd2ZWTKhMwUkSJ+On4PpaCeDFrcyZhiejlb6In5E/HB70M5W0ayJLCyb2dFotcOlThWM1sbkP70+uU8JwR8YPzjfkaKepnImsZXbfb/btqjBjET9M1TKr9brW7RlkHzrgwVjRJksTUC3EHdc0nx1ApRwdHhvALB7FzF1m0dQm4MWAJyHkPBeEvf6t4+fEj+UApb2tmrOD6Quefx80U7eMXJTRjA7fToYyz93hn+ZOWhe8pJuIMP3n8pO4FmwHFiUQiVFUJgSQvuDeg3RqTed2LVMcoiuIaSCcSs0oMhds=
  template:
    metadata:
      name: authentik-outpost-token
      namespace: monitoring
    type: Opaque
