---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgCodQz6tgzC71USJ72dKM4QBunln/pJVdHQlIJ+2S/pNnQKMwzvmWgiCh+RhediWPGYsjPP/rjXiGsavxYL5TBIAyWMSd0mraiqevwjlL6rLMVooxF0dddijYbJHl47V+gZ4ZvxxFVcDF6buN1IdxO6zrMaJ4PwgFf5gTGr5Sl1fSElq7mxWWvgVWBPYU1K0K3/faJPPx0ArxCobOg88kVAHZEbUJ5mD+ZzOXen62G5eGjU7YZn7fAoUQOYjrMe1wFV58D5420SFiYRmtbrZ1LHmRZfs3WffdL3WoFoQwgoW9ST2976pzvH516OUwqpfWdsEA8nhlD/fmSFYBdu4zmqtMz1h2b1Tkzq0dxK7SCFlLg2nGJxDaLfhgWEuZ0JmMT3wwVaCgtSKhnx9a8g2jvb0/dQHTr1N7viay5POzDF9DDPbgMzWRGodJmBwHNC6q3XCWtaEVcaMCdG6FZ1jBtuS55DPCNkhMwJFKI7sbPz3zoDgUiM1JbolJfztEz+t1WjfRvWzBkGTBPi+iiyAPbX/RIUsFYVj5muyOZYxPRTmp+z8kJSJDjXhYWN9tm9kH2KLjO/EzbAYlb2xrvU+hy1tQrqFYhX8+WUhJvcyE5V5PmCTeNnRjnWRBhDfxZ6pkRDRHsIqICT9d4xx7azIoZd+H7SSsaqE/6tGGi40xuRpZAmlNTgrqBQgG3vB55AxhCxwN/W0IxvApGYEClIMwipv4LdivZ8oGvfH+YhQCwByhrT3GIIV9UcQPUDY7ZysxdLvQ1D/vIQfFwkdE/9VlYwsc0K1zUtsl5G1V3VPqcaATJE2D5bOY2+l1VmlC0k1SrF6QxkGBKK9GJVCj/Lh1qsIG20NYlfw9an
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
