---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-discord-webhook
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    discord-webhook-url: AgBEWEj5tZ52dBVI7GT/AK85WoCZi3n3iw/YEkAb9SpQcxzVpz/qr9ZmoYFUtoxOZTF2VWPoUlKMca64fOhAhV6H4aSrMkOr3AF6bRud8yxOMEjMQoFnuHkCQLcEjz+UreZ0eHsobyXqTLZ22vOed8s+GIaPaGuuI8YdgIKNFmtG/ZludOggtYINFUMFuXFe3trZ6yQnbdyQEUF/A7cRTxJACgDt6Ma1n/SWFatY2EDE3NrdCAZDflSUi6E+987oUeMVlHFacOk0avV8QKuRnvQDNqf+tHaelC9PhUSSwyJ105kTPINC4RGGJzXbSfaf7ZoiyTHlirpWwDqlvEjV6hAybsGhy4efkM3I5EAc2RTZbDuVwlFxALGYI+5sbM1EKI4t94XnMFmWlso1fNo0zCp8kfsCqIlpjDDo3JT23/bJ4/2CxHc7rR2GP8NfHoFhZo7Hp5GL24+nzE5BL/bkBielECdg3F3N5yeCsN7eOZdkwW3g9OhPWJN8d6W/RLGoI4aF+NKwgak9pSHvCRivrSBrwbSh13skemc76MOMBhaI0hWNdPi4yOtlknbmDJ4mBrVXOQx8Ar3GeCzplO+S6w696c2fzMfAAlex1NXuzfa242PuNZ3BIypBNZA6h0tQGJU+cNsloO9Syxi02Qp+XHy/xj4sysP0p33NFq528Rs+7olHgzarV3H+Xumr4270Mwx4HVuX0RRdYGapoH1VFcj9zhrlYwWgSGGJZchtIVCCVvLlKJO4MInWJhpt7FHBEgktw1s/f0OIiVaFRZOJ03+ETaIVXvX6E/0SOwZye56n/nqnvOr/vxAl9+XyluBYaiSLfaCYAl9R6B3IQNsoOZ8pHrinsRaCnpNe
  template:
    metadata:
      name: argocd-discord-webhook
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
