apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
  labels:
    notifications.argocd/channel: none
    notifications.argocd/profile: quiet
spec:
  project: default
  source:
    repoURL: https://github.com/pablomarelli/homelab-infra.git
    targetRevision: main
    path: manifests/argocd-notifications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
