apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/PabloMarelli/home-assistant.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    syncOptions:
      - CreateNamespace=false

