apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  labels:
    notifications.argocd/channel: infra
    notifications.argocd/profile: critical
spec:
  project: default
  source:
    repoURL: https://github.com/pablomarelli/homelab-infra.git
    targetRevision: HEAD
    path: manifests/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
