apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argocd
  labels:
    notifications.argocd/channel: main
    notifications.argocd/profile: app
spec:
  project: default
  source:
    repoURL: https://github.com/pablomarelli/homelab-infra.git
    targetRevision: main
    path: manifests/umami
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
